# Generated by Django 5.1.1 on 2025-01-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_halls_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='halls',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
