# Generated by Django 5.1.1 on 2025-01-24 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_halls_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='decoration',
            name='decoration_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
