# Generated by Django 5.1.1 on 2025-01-24 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_decoration_decoration_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='food_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
