# Generated by Django 5.1.1 on 2025-01-30 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_food_food_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='event_id',
        ),
        migrations.AddField(
            model_name='bookings',
            name='decoration_value',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='event_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='event_status',
            field=models.CharField(default='pending', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='food_value',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='no_of_people',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Events',
        ),
    ]
